In [1]:
# import current working directory

import os

print(os.getcwd())

c:\Users\Greesha Vaishnavi\Desktop\dsprojects\Hotel_Booking_Cancellation_Prediction\research\model_experiments

In [2]:
# import Libraries

import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    f1_score,
    roc_auc_score,
    average_precision_score,
    log_loss
)

In [3]:
# scaled transformed data will be used for svm

train_df = pd.read_csv(
    "../../artifacts/data_transformation/train.csv"
)

test_df = pd.read_csv(
    "../../artifacts/data_transformation/test.csv"
)

print("Train shape:", train_df.shape)
print("Test shape :", test_df.shape)

Train shape: (95512, 917)
Test shape : (23878, 917)

In [4]:
# seperate features and target 

X_train = train_df.drop("is_canceled", axis=1)

y_train = train_df["is_canceled"]

X_test = test_df.drop( "is_canceled",axis=1)

y_test = test_df["is_canceled"]

In [5]:
# checking shapes 

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_test shape :", X_test.shape)
print("y_test shape :", y_test.shape)

X_train shape: (95512, 916)
y_train shape: (95512,)
X_test shape : (23878, 916)
y_test shape : (23878,)

In [6]:
# checking target distribution

print("Training target distribution:")
print(y_train.value_counts())

print("\nTraining target percentage:")
print(y_train.value_counts(normalize=True) * 100)

Training target distribution:
is_canceled
0    60133
1    35379
Name: count, dtype: int64

Training target percentage:
is_canceled
0    62.958581
1    37.041419
Name: proportion, dtype: float64

# KNN Baseline model

In [7]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [8]:
# train the model

knn_model.fit(X_train,
    y_train
)

KNeighborsClassifier()

In [9]:
# prediction

knn_pred = knn_model.predict(X_test)

knn_prob = knn_model.predict_proba(X_test)[:, 1]

In [10]:
# evaluation 

knn_cm = confusion_matrix(
    y_test,
    knn_pred
)

tn, fp, fn, tp = knn_cm.ravel()


knn_accuracy = accuracy_score(
    y_test,
    knn_pred
)

knn_precision = precision_score(
    y_test,
    knn_pred,
    zero_division=0
)

knn_recall = recall_score(
    y_test,
    knn_pred,
    zero_division=0
)

knn_specificity = tn / (tn + fp)

knn_f1 = f1_score(
    y_test,
    knn_pred,
    zero_division=0
)

knn_roc_auc = roc_auc_score(
    y_test,
    knn_prob
)

knn_pr_auc = average_precision_score(
    y_test,
    knn_prob
)

knn_logloss = log_loss(
    y_test,
    knn_prob
)

In [11]:
# display result

print("=" * 55)
print("KNN - BASELINE EVALUATION")
print("=" * 55)

print(f"Accuracy    : {knn_accuracy:.4f}")
print(f"Precision   : {knn_precision:.4f}")
print(f"Recall      : {knn_recall:.4f}")
print(f"Specificity : {knn_specificity:.4f}")
print(f"F1 Score    : {knn_f1:.4f}")
print(f"ROC-AUC     : {knn_roc_auc:.4f}")
print(f"PR-AUC      : {knn_pr_auc:.4f}")
print(f"Log Loss    : {knn_logloss:.4f}")

=======================================================
KNN - BASELINE EVALUATION
=======================================================
Accuracy    : 0.8397
Precision   : 0.7896
Recall      : 0.7734
Specificity : 0.8787
F1 Score    : 0.7814
ROC-AUC     : 0.9031
PR-AUC      : 0.8409
Log Loss    : 1.1312

In [12]:
knn_baseline_results = pd.DataFrame({
    "Model": ["KNN"],
    "Accuracy": [knn_accuracy],
    "Precision": [knn_precision],
    "Recall": [knn_recall],
    "Specificity": [knn_specificity],
    "F1 Score": [knn_f1],
    "ROC-AUC": [knn_roc_auc],
    "PR-AUC": [knn_pr_auc],
    "Log Loss": [knn_logloss]
})

knn_baseline_results.round(4)

,Model,Accuracy,Precision,Recall,Specificity,F1 Score,ROC-AUC,PR-AUC,Log Loss
0,KNN,0.8397,0.7896,0.7734,0.8787,0.7814,0.9031,0.8409,1.1312

In [20]:
# KNN n_neighbour experiment 

k_values = [3, 5, 7, 11]

knn_k_results = []

for k in k_values:

    model = KNeighborsClassifier(
        n_neighbors=k,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    test_pred = model.predict(
        X_test
    )

    test_prob = model.predict_proba(
        X_test
    )[:, 1]

    cm = confusion_matrix(
        y_test,
        test_pred
    )

    tn, fp, fn, tp = cm.ravel()

    accuracy = accuracy_score(
        y_test,
        test_pred
    )

    precision = precision_score(
        y_test,
        test_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        test_pred,
        zero_division=0
    )

    specificity = tn / (tn + fp)

    f1 = f1_score(
        y_test,
        test_pred,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_prob
    )

    pr_auc = average_precision_score(
        y_test,
        test_prob
    )

    logloss = log_loss(
        y_test,
        test_prob
    )

    knn_k_results.append({
        "K": k,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "Specificity": specificity,
        "F1 Score": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Log Loss": logloss
    })

In [21]:
# creating dataframe 

knn_k_results_df = pd.DataFrame(
    knn_k_results
)

knn_k_results_df.round(4)

,K,Accuracy,Precision,Recall,Specificity,F1 Score,ROC-AUC,PR-AUC,Log Loss
0,3,0.8360,0.7773,0.7810,0.8684,0.7792,0.8884,0.8024,2.0570
1,5,0.8397,0.7896,0.7734,0.8787,0.7814,0.9031,0.8409,1.1312
2,7,0.8412,0.7958,0.7683,0.8840,0.7818,0.9083,0.8568,0.7905
3,11,0.8394,0.7985,0.7577,0.8875,0.7776,0.9108,0.8677,0.5297

# hyper parameter tuning

In [22]:
# import gridsearch cv

from sklearn.model_selection import GridSearchCV

In [23]:
# parameter grid

knn_param_grid = {
    "n_neighbors": [5, 7, 11],
    "weights": ["uniform", "distance"]
}

In [24]:
# create gridsearch cv 

knn_grid_search = GridSearchCV(
    estimator=KNeighborsClassifier(
        n_jobs=-1
    ),
    param_grid=knn_param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1,
    verbose=1
)

In [25]:
# model fit 

knn_grid_search.fit(X_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_jobs=-1), n_jobs=-1,
             param_grid={'n_neighbors': [5, 7, 11],
                         'weights': ['uniform', 'distance']},
             scoring='f1', verbose=1)

In [26]:
# get the best parameter

print("Best Parameters:")
print(knn_grid_search.best_params_)

print("\nBest CV F1 Score:")
print(knn_grid_search.best_score_)

Best Parameters:
{'n_neighbors': 11, 'weights': 'distance'}

Best CV F1 Score:
0.7990246275305845

In [30]:
# estimator from gridsearchcv

knn_tuned = knn_grid_search.best_estimator_

In [31]:
# make the prediction and probability of tunned model

knn_tuned_pred = knn_tuned.predict(
    X_test
)

knn_tuned_prob = knn_tuned.predict_proba(
    X_test
)[:, 1]

In [32]:
knn_tuned_cm = confusion_matrix(
    y_test,
    knn_tuned_pred
)

tn, fp, fn, tp = knn_tuned_cm.ravel()


knn_tuned_accuracy = accuracy_score(
    y_test,
    knn_tuned_pred
)

knn_tuned_precision = precision_score(
    y_test,
    knn_tuned_pred,
    zero_division=0
)

knn_tuned_recall = recall_score(
    y_test,
    knn_tuned_pred,
    zero_division=0
)

knn_tuned_specificity = tn / (tn + fp)

knn_tuned_f1 = f1_score(
    y_test,
    knn_tuned_pred,
    zero_division=0
)

knn_tuned_roc_auc = roc_auc_score(
    y_test,
    knn_tuned_prob
)

knn_tuned_pr_auc = average_precision_score(
    y_test,
    knn_tuned_prob
)

knn_tuned_logloss = log_loss(
    y_test,
    knn_tuned_prob
)

In [33]:
# display result

print("=" * 55)
print("KNN - TUNED MODEL EVALUATION")
print("=" * 55)

print(f"Accuracy    : {knn_tuned_accuracy:.4f}")
print(f"Precision   : {knn_tuned_precision:.4f}")
print(f"Recall      : {knn_tuned_recall:.4f}")
print(f"Specificity : {knn_tuned_specificity:.4f}")
print(f"F1 Score    : {knn_tuned_f1:.4f}")
print(f"ROC-AUC     : {knn_tuned_roc_auc:.4f}")
print(f"PR-AUC      : {knn_tuned_pr_auc:.4f}")
print(f"Log Loss    : {knn_tuned_logloss:.4f}")

=======================================================
KNN - TUNED MODEL EVALUATION
=======================================================
Accuracy    : 0.8602
Precision   : 0.8213
Recall      : 0.7957
Specificity : 0.8982
F1 Score    : 0.8083
ROC-AUC     : 0.9304
PR-AUC      : 0.9057
Log Loss    : 0.5583

In [34]:
# baseline vs tuned model compare

knn_comparison = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "Specificity",
        "F1 Score",
        "ROC-AUC",
        "PR-AUC",
        "Log Loss"
    ],

    "Baseline": [
        knn_accuracy,
        knn_precision,
        knn_recall,
        knn_specificity,
        knn_f1,
        knn_roc_auc,
        knn_pr_auc,
        knn_logloss
    ],

    "Tuned": [
        knn_tuned_accuracy,
        knn_tuned_precision,
        knn_tuned_recall,
        knn_tuned_specificity,
        knn_tuned_f1,
        knn_tuned_roc_auc,
        knn_tuned_pr_auc,
        knn_tuned_logloss
    ]
})

knn_comparison.round(4)

        Metric  Baseline   Tuned
0     Accuracy    0.8397  0.8602
1    Precision    0.7896  0.8213
2       Recall    0.7734  0.7957
3  Specificity    0.8787  0.8982
4     F1 Score    0.7814  0.8083
5      ROC-AUC    0.9031  0.9304
6       PR-AUC    0.8409  0.9057
7     Log Loss    1.1312  0.5583